"""
Clinical Report Generator.

Generates structured clinical reports that translate model predictions
into actionable clinical information. Designed to match what a
clinician would need to make an informed decision.
"""

import json
import numpy as np
import pandas as pd
from datetime import datetime
from typing import Dict, List, Optional
from pathlib import Path

from genomicguard.config import REPORTS_DIR, DashboardConfig


class ClinicalReportGenerator:
    """
    Generates clinical-grade reports from model predictions.

    Each report includes:
    - Risk assessment summary
    - Contributing genomic and clinical factors
    - Confidence intervals
    - Actionable recommendations
    - Model transparency section
    """

    def __init__(self):
        self.dashboard_config = DashboardConfig()

    def generate_patient_report(
        self,
        patient_id: str,
        risk_scores: Dict[str, float],
        shap_explanation: Dict,
        patient_features: Dict,
        confidence_interval: Optional[Dict] = None,
        variant_classifications: Optional[Dict] = None,
    ) -> Dict:
        """
        Generate a comprehensive clinical report for a patient.

        Args:
            patient_id: Patient identifier
            risk_scores: Dict of disease → risk probability
            shap_explanation: SHAP explanation dict from SHAPExplainer
            patient_features: Dict of clinical feature values
            confidence_interval: Optional CI dict with lower/upper bounds
            variant_classifications: Optional variant classification results

        Returns:
            Structured report dictionary
        """
        # Determine overall risk level
        max_risk = max(risk_scores.values())
        risk_level = self._classify_risk(max_risk)

        # Build report
        report = {
            "report_id": f"RPT-{datetime.now().strftime('%Y%m%d%H%M%S')}-{patient_id}",
            "generated_at": datetime.now().isoformat(),
            "patient_id": patient_id,
            "disclaimer": (
                "This report is generated by an AI system for research purposes only. "
                "It should not be used as a substitute for professional medical advice. "
                "All findings should be reviewed and validated by a qualified healthcare provider."
            ),

            # Risk Summary
            "risk_summary": {
                "overall_risk_level": risk_level,
                "overall_risk_score": float(max_risk),
                "disease_risks": {
                    disease: {
                        "risk_score": float(score),
                        "risk_level": self._classify_risk(score),
                        "percentile": None,  # Would be computed from population data
                    }
                    for disease, score in risk_scores.items()
                },
                "confidence_interval": confidence_interval,
            },

            # Contributing Factors
            "contributing_factors": {
                "top_risk_factors": self._format_risk_factors(
                    shap_explanation.get("top_risk_factors", [])
                ),
                "top_protective_factors": self._format_risk_factors(
                    shap_explanation.get("top_protective_factors", [])
                ),
                "genetic_contribution": self._estimate_genetic_contribution(shap_explanation),
                "clinical_contribution": self._estimate_clinical_contribution(shap_explanation),
            },

            # Clinical Context
            "clinical_context": {
                "patient_demographics": self._extract_demographics(patient_features),
                "key_lab_values": self._extract_lab_values(patient_features),
                "lifestyle_factors": self._extract_lifestyle(patient_features),
            },

            # Variant Analysis
            "variant_analysis": variant_classifications,

            # Recommendations
            "recommendations": self._generate_recommendations(
                risk_scores, risk_level, patient_features
            ),

            # Model Transparency
            "model_transparency": {
                "model_type": "Gradient Boosting Ensemble with Calibrated Probabilities",
                "explanation_method": "SHAP (SHapley Additive exPlanations)",
                "calibration": "Platt scaling via CalibratedClassifierCV",
                "n_features_used": len(shap_explanation.get("all_contributions", [])),
                "base_risk": shap_explanation.get("base_risk", None),
            },
        }

        return report

    def _classify_risk(self, score: float) -> str:
        """Classify risk score into categorical level."""
        thresholds = self.dashboard_config.risk_thresholds
        if score < thresholds["low"]:
            return "Low"
        elif score < thresholds["moderate"]:
            return "Moderate"
        elif score < thresholds["high"]:
            return "High"
        return "Very High"

    def _format_risk_factors(self, factors: List[Dict]) -> List[Dict]:
        """Format risk factors for clinical report."""
        formatted = []
        for f in factors[:10]:
            feature_name = f.get("feature", "")
            clean_name = feature_name.replace("clinical_", "").replace("_", " ").title()

            formatted.append({
                "factor": clean_name,
                "impact": f.get("direction", "unknown"),
                "magnitude": round(f.get("magnitude", 0), 4),
                "patient_value": round(f.get("value", 0), 2),
            })
        return formatted

    def _estimate_genetic_contribution(self, explanation: Dict) -> float:
        """Estimate the proportion of risk attributable to genetic factors."""
        contributions = explanation.get("all_contributions", [])
        genetic_keywords = ["prs", "pc_", "interact_", "snp"]

        total_shap = sum(abs(c["shap_value"]) for c in contributions)
        if total_shap == 0:
            return 0.0

        genetic_shap = sum(
            abs(c["shap_value"])
            for c in contributions
            if any(kw in c["feature"].lower() for kw in genetic_keywords)
        )
        return round(genetic_shap / total_shap, 3)

    def _estimate_clinical_contribution(self, explanation: Dict) -> float:
        """Estimate the proportion of risk attributable to clinical factors."""
        return round(1.0 - self._estimate_genetic_contribution(explanation), 3)

    def _extract_demographics(self, features: Dict) -> Dict:
        """Extract demographic information from features."""
        return {
            "age": features.get("clinical_age", features.get("age", "N/A")),
            "bmi": features.get("clinical_bmi", features.get("bmi", "N/A")),
        }

    def _extract_lab_values(self, features: Dict) -> Dict:
        """Extract key lab values."""
        lab_keys = [
            "fasting_glucose", "total_cholesterol", "hdl_cholesterol",
            "ldl_cholesterol", "triglycerides", "hba1c", "systolic_bp",
        ]
        labs = {}
        for key in lab_keys:
            for prefix in ["clinical_", ""]:
                full_key = f"{prefix}{key}"
                if full_key in features:
                    labs[key.replace("_", " ").title()] = features[full_key]
                    break
        return labs

    def _extract_lifestyle(self, features: Dict) -> Dict:
        """Extract lifestyle factors."""
        smoking_map = {0: "Never", 1: "Former", 2: "Current"}
        smoking_val = features.get("clinical_smoking_status", features.get("smoking_status", 0))
        # Handle numpy types
        if hasattr(smoking_val, 'item'):
            smoking_val = smoking_val.item()
        smoking_val = int(round(float(smoking_val)))

        exercise_val = features.get("clinical_exercise_hours_week", features.get("exercise_hours_week", 0))
        family_val = features.get("clinical_family_history", features.get("family_history", 0))

        return {
            "smoking_status": smoking_map.get(smoking_val, "Unknown"),
            "exercise_hours_per_week": round(float(exercise_val), 1),
            "family_history": "Yes" if float(family_val) > 0.5 else "No",
        }

    def _generate_recommendations(
        self, risk_scores: Dict, risk_level: str, features: Dict
    ) -> List[Dict]:
        """Generate actionable clinical recommendations."""
        recommendations = []

        if risk_level in ["High", "Very High"]:
            recommendations.append({
                "priority": "HIGH",
                "category": "Follow-up",
                "recommendation": "Recommend comprehensive clinical evaluation with a specialist.",
                "rationale": f"Overall risk assessment indicates {risk_level.lower()} risk."
            })

        # Disease-specific recommendations
        for disease, score in risk_scores.items():
            if score > 0.6:
                if "diabetes" in disease.lower():
                    recommendations.append({
                        "priority": "MODERATE",
                        "category": "Screening",
                        "recommendation": "Consider HbA1c monitoring and oral glucose tolerance test.",
                        "rationale": f"Elevated Type 2 Diabetes risk score ({score:.2f})."
                    })
                elif "coronary" in disease.lower():
                    recommendations.append({
                        "priority": "MODERATE",
                        "category": "Screening",
                        "recommendation": "Consider lipid panel review and cardiovascular risk assessment.",
                        "rationale": f"Elevated Coronary Artery Disease risk score ({score:.2f})."
                    })
                elif "breast" in disease.lower() or "cancer" in disease.lower():
                    recommendations.append({
                        "priority": "MODERATE",
                        "category": "Screening",
                        "recommendation": "Consider enhanced screening protocol discussion with oncology.",
                        "rationale": f"Elevated cancer risk score ({score:.2f})."
                    })

        # Lifestyle recommendations
        recommendations.append({
            "priority": "GENERAL",
            "category": "Lifestyle",
            "recommendation": "Continue regular physical activity and balanced nutrition.",
            "rationale": "Evidence-based lifestyle factors contribute to disease risk reduction."
        })

        return recommendations

    def save_report(self, report: Dict, output_dir: Optional[Path] = None) -> Path:
        """Save report as JSON."""
        out = output_dir or REPORTS_DIR
        out.mkdir(parents=True, exist_ok=True)

        filepath = out / f"{report['report_id']}.json"
        with open(filepath, "w") as f:
            json.dump(report, f, indent=2, default=str)

        return filepath
